version: ~> 1.0

language: node_js

node_js:
- 14.19.1

cache: yarn

script:
    - npm run build

deploy:
    provider: pages
    local_dir: public
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      branch: master
